# Generated by Django 5.2.17 on 2026-10-06 10:55

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('current_location', models.CharField(max_length=500)),
                ('pickup_location', models.CharField(max_length=500)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PLANNED', 'PLANNED'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'), models.Index(fields=['-created'], name='trips_trip_created_498b18_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField()),
                ('off_duty_hours', models.FloatField(default=0.0)),
                ('sleeper_hours', models.FloatField(default=0.0)),
                ('driving_hours', models.FloatField(default=0.0)),
                ('on_duty_hours', models.FloatField(default=0.0)),
                ('total_hours', models.FloatField(default=0.0)),
                ('cycle_hours_after_day', models.FloatField(default=0.0)),
                ('cycle_remaining', models.FloatField(default=0.0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('trip', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TripDailyLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sequence', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('off_duty', 'off_duty'), ('sleeper', 'sleeper'), ('driving', 'driving'), ('on_duty_not_driving', 'on_duty_not_driving')], max_length=30)),
                ('start_hour', models.FloatField()),
                ('end_hour', models.FloatField()),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('start_miles', models.FloatField(default=0.0)),
                ('end_miles', models.FloatField(default=0.0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trips.tripdailylog')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TripRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('total_miles', models.FloatField(default=0.0)),
                ('total_duration_hours', models.FloatField(default=0.0)),
                ('legs_summary', models.JSONField(default=list)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='trips.trip')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripRouteGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('points', models.JSONField(default=list)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='trips.triproute')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('role', models.CharField(choices=[('origin', 'origin'), ('pickup', 'pickup'), ('dropoff', 'dropoff')], max_length=20)),
                ('query', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=500)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.trip')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('trip', 'role')},
            },
        ),
        migrations.CreateModel(
            name='TripSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sequence', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('off_duty', 'off_duty'), ('sleeper', 'sleeper'), ('driving', 'driving'), ('on_duty_not_driving', 'on_duty_not_driving')], max_length=30)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('hours', models.FloatField()),
                ('start_miles', models.FloatField(default=0.0)),
                ('end_miles', models.FloatField(default=0.0)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['trip', 'sequence'], name='trips_trips_trip_id_d04206_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sequence', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('pickup', 'pickup'), ('dropoff', 'dropoff'), ('fuel', 'fuel'), ('break', 'break'), ('rest', 'rest'), ('stop', 'stop')], max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('miles', models.FloatField(default=0.0)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(max_length=30)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('hours', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['trip', 'sequence'], name='trips_trips_trip_id_54bb53_idx')],
            },
        ),
    ]
